apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: designsystemet-figma-slack-app
  namespace: designsystem
  labels:
    team: designsystem
spec:
  image: {{ image }}
  #image: ghcr.io/navikt/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
  #       ^--- interpolated from the ${{ env.docker_image }} variable in the action
