apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: designsystemet-figma-slack-app
  namespace: designsystem
  labels:
    team: designsystem
spec:
  image: {{ image }}
  envFrom:
    - secret: ds-figma-slack
    - secret: ds-figma-slack-token
    - secret: ds-figma-slack-passcode
    - secret: ds-figma-token
  port: 3000
  ingresses:
    - https://designsystemet-figma-slack-app.ekstern.dev.nav.no
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isalive
  readiness:
    path: /isready